ktor:
  application:
    modules:
      - moe.luminolmc.ApplicationKt.module
  deployment:
    port: 8080
auth:
  token: ""
db:
  mongo:
    host: "127.0.0.1"
    port: 27017
    database:
      name: "luminol"