ktor:
  application:
    modules:
      - moe.luminolmc.ApplicationKt.module
  deployment:
    port: 8080
jwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "luminol-website"
  secret: "114514114514"
db:
  mongo:
    host: "127.0.0.1"
    port: 27017
    database:
      name: "luminol"